import { useEffect, useMemo, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import api from "../api/axiosConfig";

const categories = [
  { id: "users", label: "Users" },
  { id: "bookings", label: "Bookings" },
  { id: "incidents", label: "Incidents" },
  { id: "maintenance", label: "Maintenance" },
  { id: "assets", label: "Assets" },
  { id: "notifications", label: "Notifications" },
];

function formatDate(value) {
  if (!value) {
    return "-";
  }
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return "-";
  }
  return date.toLocaleString();
}

function getPercent(part, whole) {
  if (!whole) {
    return 0;
  }
  return Number(((part / whole) * 100).toFixed(1));
}

function createPdfHeader(doc, title, subtitle) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 34, "F");

  doc.setTextColor(34, 211, 238);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("UNIOPS ADMIN REPORT", 14, 10);

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 14, 20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(203, 213, 225);
  doc.text(subtitle, 14, 27);

  doc.setDrawColor(8, 47, 73);
  doc.setLineWidth(0.6);
  doc.line(14, 36, 196, 36);
}

function createPdfFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.2);
    doc.line(14, 286, 196, 286);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text(
      `Generated by UniOps Analytics on ${new Date().toLocaleString()} | Page ${i}/${pageCount}`,
      14,
      292,
    );
  }
}

function Analytics({ user, onBack }) {
  const [activeCategory, setActiveCategory] = useState("users");
  const [dashboard, setDashboard] = useState(null);
  const [notifications, setNotifications] = useState([]);
  const [incidents, setIncidents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const totalUsers = dashboard?.totalUsers ?? 0;
  const blockedUsers = dashboard?.blockedUsers ?? 0;
  const activeUsers = Math.max(0, totalUsers - blockedUsers);
  const totalLogins = dashboard?.totalLogins ?? 0;
  const users = dashboard?.users || [];
  const loginChart = dashboard?.loginChart || [];

  const activePercent = getPercent(activeUsers, totalUsers);
  const blockedPercent = getPercent(blockedUsers, totalUsers);

  const loginBars = useMemo(() => {
    const ranked = [...loginChart].sort(
      (a, b) => (b.loginCount || 0) - (a.loginCount || 0),
    );
    const top = ranked.slice(0, 8);
    const peak = Math.max(1, ...top.map((item) => item.loginCount || 0));

    return top.map((item) => ({
      ...item,
      barPercent: ((item.loginCount || 0) / peak) * 100,
    }));
  }, [loginChart]);

  const notificationsWithAttachment = useMemo(
    () => notifications.filter((item) => item.hasDocument).length,
    [notifications],
  );

  const notificationsWithLinks = useMemo(
    () => notifications.filter((item) => item.linkUrl).length,
    [notifications],
  );

  const incidentStatusCounts = useMemo(() => {
    const counts = {
      OPEN: 0,
      IN_PROGRESS: 0,
      RESOLVED: 0,
      CLOSED: 0,
      REJECTED: 0,
    };
    incidents.forEach((item) => {
      const key = (item.status || "").toUpperCase();
      if (counts[key] != null) {
        counts[key] += 1;
      }
    });
    return counts;
  }, [incidents]);

  const incidentPriorityCounts = useMemo(() => {
    const counts = { LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0 };
    incidents.forEach((item) => {
      const key = (item.priority || "").toUpperCase();
      if (counts[key] != null) {
        counts[key] += 1;
      }
    });
    return counts;
  }, [incidents]);

  const incidentMonthlyTrend = useMemo(() => {
    const months = [];
    for (let i = 5; i >= 0; i -= 1) {
      const date = new Date();
      date.setMonth(date.getMonth() - i);
      const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
      months.push({
        key,
        label: date.toLocaleString(undefined, { month: "short" }),
        count: 0,
      });
    }
    incidents.forEach((item) => {
      const created = new Date(item.createdAt);
      if (Number.isNaN(created.getTime())) {
        return;
      }
      const key = `${created.getFullYear()}-${String(created.getMonth() + 1).padStart(2, "0")}`;
      const target = months.find((month) => month.key === key);
      if (target) {
        target.count += 1;
      }
    });
    const peak = Math.max(1, ...months.map((month) => month.count));
    return months.map((month) => ({
      ...month,
      barPercent: (month.count / peak) * 100,
    }));
  }, [incidents]);

  const incidentResolutionHours = useMemo(() => {
    const values = incidents
      .map((item) => {
        const created = new Date(item.createdAt);
        const resolved = new Date(item.resolvedAt || item.closedAt);
        if (Number.isNaN(created.getTime()) || Number.isNaN(resolved.getTime())) {
          return null;
        }
        const diffHours = (resolved.getTime() - created.getTime()) / (1000 * 60 * 60);
        return diffHours >= 0 ? diffHours : null;
      })
      .filter((value) => value != null);
    if (values.length === 0) {
      return 0;
    }
    const avg = values.reduce((sum, value) => sum + value, 0) / values.length;
    return Number(avg.toFixed(1));
  }, [incidents]);

  useEffect(() => {
    const load = async () => {
      setLoading(true);
      setError("");

      try {
        const [dashboardResponse, notificationsResponse, incidentsResponse] = await Promise.all([
          api.get("/admin/dashboard"),
          api.get("/notifications"),
          api.get("/incidents"),
        ]);

        if (dashboardResponse.data?.success) {
          setDashboard(dashboardResponse.data.data);
        } else {
          setError(
            dashboardResponse.data?.message || "Unable to load analytics data.",
          );
        }

        if (notificationsResponse.data?.success) {
          setNotifications(notificationsResponse.data.data || []);
        }
        if (incidentsResponse.data?.success) {
          setIncidents(incidentsResponse.data.data || []);
        }
      } catch (err) {
        setError(
          err.response?.data?.message || "Unable to load analytics data.",
        );
      } finally {
        setLoading(false);
      }
    };

    load();
  }, []);

  const exportUsersPdf = () => {
    const doc = new jsPDF("p", "mm", "a4");
    createPdfHeader(
      doc,
      "Users Analytics Report",
      `${user?.name || "Admin"} | ${new Date().toLocaleDateString()}`,
    );

    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.text("Executive Summary", 14, 46);

    autoTable(doc, {
      startY: 50,
      theme: "grid",
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255] },
      body: [
        ["Total Users", totalUsers],
        ["Active Users", `${activeUsers} (${activePercent}%)`],
        ["Blocked Users", `${blockedUsers} (${blockedPercent}%)`],
        ["Total Login Events", totalLogins],
      ],
      columnStyles: {
        0: {
          fontStyle: "bold",
          fillColor: [241, 245, 249],
          textColor: [15, 23, 42],
        },
      },
      margin: { left: 14, right: 14 },
    });

    const tableRows = users.map((item) => [
      item.name || "-",
      item.email || "-",
      item.role || "-",
      item.blocked ? "Blocked" : "Active",
      item.loginCount ?? 0,
      formatDate(item.lastLoginAt),
      formatDate(item.createdAt),
    ]);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [
        ["Name", "Email", "Role", "Status", "Logins", "Last Login", "Created"],
      ],
      body: tableRows,
      styles: { fontSize: 8.6, cellPadding: 2.4 },
      headStyles: { fillColor: [8, 47, 73], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 },
      didDrawPage: () => {
        createPdfFooter(doc);
      },
    });

    createPdfFooter(doc);
    doc.save(
      `uniops-users-report-${new Date().toISOString().slice(0, 10)}.pdf`,
    );
  };

  const exportUsersExcel = () => {
    const summaryRows = [
      { Metric: "Total Users", Value: totalUsers },
      {
        Metric: "Active Users",
        Value: activeUsers,
        Percentage: `${activePercent}%`,
      },
      {
        Metric: "Blocked Users",
        Value: blockedUsers,
        Percentage: `${blockedPercent}%`,
      },
      { Metric: "Total Login Events", Value: totalLogins },
    ];

    const userRows = users.map((item) => ({
      Name: item.name || "-",
      Email: item.email || "-",
      Role: item.role || "-",
      Status: item.blocked ? "Blocked" : "Active",
      "Login Count": item.loginCount ?? 0,
      "Last Login": formatDate(item.lastLoginAt),
      "Created At": formatDate(item.createdAt),
    }));

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(summaryRows),
      "Summary",
    );
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(userRows),
      "Users",
    );

    XLSX.writeFile(
      workbook,
      `uniops-users-report-${new Date().toISOString().slice(0, 10)}.xlsx`,
    );
  };

  const exportNotificationsPdf = () => {
    const doc = new jsPDF("p", "mm", "a4");
    createPdfHeader(
      doc,
      "Notifications Report",
      `${user?.name || "Admin"} | ${new Date().toLocaleDateString()}`,
    );

    autoTable(doc, {
      startY: 44,
      theme: "grid",
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255] },
      body: [
        ["Total Notifications", notifications.length],
        ["With Attachments", notificationsWithAttachment],
        ["With Links", notificationsWithLinks],
      ],
      margin: { left: 14, right: 14 },
      columnStyles: {
        0: {
          fontStyle: "bold",
          fillColor: [241, 245, 249],
          textColor: [15, 23, 42],
        },
      },
    });

    const rows = notifications.map((item) => [
      item.title || "-",
      item.createdBy || "-",
      item.linkUrl ? "Yes" : "No",
      item.hasDocument ? "Yes" : "No",
      formatDate(item.createdAt),
    ]);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Title", "Created By", "Has Link", "Has Document", "Created"]],
      body: rows,
      styles: { fontSize: 9, cellPadding: 2.4 },
      headStyles: { fillColor: [8, 47, 73], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 },
      didDrawPage: () => {
        createPdfFooter(doc);
      },
    });

    createPdfFooter(doc);
    doc.save(
      `uniops-notifications-report-${new Date().toISOString().slice(0, 10)}.pdf`,
    );
  };

  const exportNotificationsExcel = () => {
    const summaryRows = [
      { Metric: "Total Notifications", Value: notifications.length },
      { Metric: "With Attachments", Value: notificationsWithAttachment },
      { Metric: "With Links", Value: notificationsWithLinks },
    ];

    const details = notifications.map((item) => ({
      Title: item.title || "-",
      Message: item.message || "-",
      "Created By": item.createdBy || "-",
      "Has Link": item.linkUrl ? "Yes" : "No",
      "Link URL": item.linkUrl || "-",
      "Has Attachment": item.hasDocument ? "Yes" : "No",
      "Attachment Name": item.documentName || "-",
      "Document URL": item.documentUrl || "-",
      "Created At": formatDate(item.createdAt),
    }));

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(summaryRows),
      "Summary",
    );
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(details),
      "Notifications",
    );

    XLSX.writeFile(
      workbook,
      `uniops-notifications-report-${new Date().toISOString().slice(0, 10)}.xlsx`,
    );
  };

  const exportIncidentsPdf = () => {
    const doc = new jsPDF("p", "mm", "a4");
    createPdfHeader(
      doc,
      "Incident Tickets Report",
      `${user?.name || "Admin"} | ${new Date().toLocaleDateString()}`,
    );

    autoTable(doc, {
      startY: 44,
      theme: "grid",
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255] },
      body: [
        ["Total Tickets", incidents.length],
        ["Open", incidentStatusCounts.OPEN],
        ["In Progress", incidentStatusCounts.IN_PROGRESS],
        ["Resolved", incidentStatusCounts.RESOLVED],
        ["Closed", incidentStatusCounts.CLOSED],
        ["Rejected", incidentStatusCounts.REJECTED],
        ["Average Resolution Time (hrs)", incidentResolutionHours],
      ],
      margin: { left: 14, right: 14 },
      columnStyles: {
        0: {
          fontStyle: "bold",
          fillColor: [241, 245, 249],
          textColor: [15, 23, 42],
        },
      },
    });

    const rows = incidents.map((item) => [
      item.id || "-",
      item.resourceName || "-",
      item.priority || "-",
      item.status || "-",
      item.assignedToName || "-",
      item.createdByName || "-",
      formatDate(item.createdAt),
    ]);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["ID", "Resource", "Priority", "Status", "Assigned To", "Reporter", "Created"]],
      body: rows,
      styles: { fontSize: 8.5, cellPadding: 2.3 },
      headStyles: { fillColor: [8, 47, 73], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 },
      didDrawPage: () => {
        createPdfFooter(doc);
      },
    });

    createPdfFooter(doc);
    doc.save(
      `uniops-incidents-report-${new Date().toISOString().slice(0, 10)}.pdf`,
    );
  };

  const exportIncidentsExcel = () => {
    const summaryRows = [
      { Metric: "Total Tickets", Value: incidents.length },
      { Metric: "Open", Value: incidentStatusCounts.OPEN },
      { Metric: "In Progress", Value: incidentStatusCounts.IN_PROGRESS },
      { Metric: "Resolved", Value: incidentStatusCounts.RESOLVED },
      { Metric: "Closed", Value: incidentStatusCounts.CLOSED },
      { Metric: "Rejected", Value: incidentStatusCounts.REJECTED },
      { Metric: "Avg Resolution Time (hrs)", Value: incidentResolutionHours },
    ];

    const details = incidents.map((item) => ({
      ID: item.id || "-",
      Resource: item.resourceName || "-",
      Location: item.location || "-",
      Category: item.category || "-",
      Priority: item.priority || "-",
      Status: item.status || "-",
      Reporter: item.createdByName || "-",
      "Reporter Email": item.createdByEmail || "-",
      "Assigned To": item.assignedToName || "-",
      "Assigned Email": item.assignedToEmail || "-",
      "Comments Count": item.comments?.length || 0,
      "Attachments Count": item.attachments?.length || 0,
      "Created At": formatDate(item.createdAt),
      "Resolved At": formatDate(item.resolvedAt),
      "Closed At": formatDate(item.closedAt),
    }));

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(summaryRows),
      "Summary",
    );
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(details),
      "Incidents",
    );

    XLSX.writeFile(
      workbook,
      `uniops-incidents-report-${new Date().toISOString().slice(0, 10)}.xlsx`,
    );
  };

  const pieCircleLength = 2 * Math.PI * 54;
  const blockedArcLength = (blockedPercent / 100) * pieCircleLength;

  return (
    <main className="relative overflow-hidden">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,_rgba(56,189,248,0.16),_transparent_35%),radial-gradient(circle_at_80%_0%,_rgba(16,185,129,0.14),_transparent_35%),radial-gradient(circle_at_70%_80%,_rgba(251,191,36,0.1),_transparent_38%)]" />

      <section className="relative mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">
              Admin Intelligence
            </p>
            <h1 className="mt-2 text-4xl font-black text-white">
              Analytics Center
            </h1>
            <p className="mt-2 text-sm text-slate-300">
              Build reports and monitor platform activity with executive-level
              summaries.
            </p>
          </div>
          <button
            type="button"
            onClick={onBack}
            className="rounded-xl border border-slate-700 bg-slate-900/70 px-4 py-2 text-sm font-semibold text-slate-200 transition hover:border-cyan-400/50 hover:bg-slate-800"
          >
            Back to Dashboard
          </button>
        </div>

        <div className="mt-6 flex flex-wrap gap-2">
          {categories.map((category) => (
            <button
              key={category.id}
              type="button"
              onClick={() => setActiveCategory(category.id)}
              className={`rounded-xl px-4 py-2 text-sm font-semibold transition ${
                activeCategory === category.id
                  ? "bg-cyan-500 text-slate-950"
                  : "border border-slate-700 bg-slate-900/70 text-slate-200 hover:border-cyan-500/60 hover:bg-slate-800"
              }`}
            >
              {category.label}
            </button>
          ))}
        </div>

        {error && (
          <div className="mt-6 rounded-2xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">
            {error}
          </div>
        )}

        {loading ? (
          <div className="mt-6 rounded-3xl border border-slate-800 bg-slate-900/80 p-6 text-slate-300">
            Loading analytics data...
          </div>
        ) : (
          <>
            {activeCategory === "users" && (
              <section className="mt-6 grid gap-6">
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                  <MetricCard
                    label="Total Users"
                    value={totalUsers}
                    accent="cyan"
                  />
                  <MetricCard
                    label="Active Users"
                    value={`${activeUsers} (${activePercent}%)`}
                    accent="emerald"
                  />
                  <MetricCard
                    label="Blocked Users"
                    value={`${blockedUsers} (${blockedPercent}%)`}
                    accent="rose"
                  />
                  <MetricCard
                    label="Total Logins"
                    value={totalLogins}
                    accent="amber"
                  />
                </div>

                <div className="grid gap-6 lg:grid-cols-[1.6fr,1fr]">
                  <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                    <div className="flex items-center justify-between gap-3">
                      <h2 className="text-xl font-bold text-white">
                        User Login Activity
                      </h2>
                      <span className="text-xs uppercase tracking-[0.2em] text-slate-400">
                        Top active users
                      </span>
                    </div>
                    <div className="mt-5 space-y-4">
                      {loginBars.length === 0 ? (
                        <p className="text-sm text-slate-300">
                          No login activity data available.
                        </p>
                      ) : (
                        loginBars.map((item) => (
                          <div key={item.id}>
                            <div className="mb-1 flex items-center justify-between text-sm">
                              <span className="truncate pr-3 font-semibold text-slate-200">
                                {item.name}
                              </span>
                              <span className="text-cyan-300">
                                {item.loginCount} logins
                              </span>
                            </div>
                            <div className="h-2.5 rounded-full bg-slate-800">
                              <div
                                className="h-2.5 rounded-full bg-gradient-to-r from-cyan-400 via-blue-500 to-indigo-500"
                                style={{
                                  width: `${Math.max(item.barPercent, 4)}%`,
                                }}
                              />
                            </div>
                          </div>
                        ))
                      )}
                    </div>
                  </article>

                  <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                    <h2 className="text-xl font-bold text-white">
                      Active vs Blocked
                    </h2>
                    <p className="mt-1 text-sm text-slate-300">
                      User distribution by account status.
                    </p>
                    <div className="mt-5 flex flex-col items-center">
                      <svg
                        width="170"
                        height="170"
                        viewBox="0 0 170 170"
                        className="drop-shadow"
                      >
                        <circle
                          cx="85"
                          cy="85"
                          r="54"
                          fill="none"
                          stroke="#1e293b"
                          strokeWidth="20"
                        />
                        <circle
                          cx="85"
                          cy="85"
                          r="54"
                          fill="none"
                          stroke="#f43f5e"
                          strokeWidth="20"
                          strokeDasharray={`${blockedArcLength} ${pieCircleLength - blockedArcLength}`}
                          strokeLinecap="round"
                          transform="rotate(-90 85 85)"
                        />
                        <circle
                          cx="85"
                          cy="85"
                          r="54"
                          fill="none"
                          stroke="#10b981"
                          strokeWidth="20"
                          strokeDasharray={`${pieCircleLength - blockedArcLength} ${blockedArcLength}`}
                          strokeDashoffset={-blockedArcLength}
                          strokeLinecap="round"
                          transform="rotate(-90 85 85)"
                        />
                        <text
                          x="85"
                          y="84"
                          textAnchor="middle"
                          fill="#ffffff"
                          fontSize="20"
                          fontWeight="700"
                        >
                          {totalUsers}
                        </text>
                        <text
                          x="85"
                          y="102"
                          textAnchor="middle"
                          fill="#94a3b8"
                          fontSize="10"
                        >
                          Users
                        </text>
                      </svg>
                      <div className="mt-5 w-full space-y-2 text-sm">
                        <LegendRow
                          label="Active"
                          value={`${activeUsers} (${activePercent}%)`}
                          tone="emerald"
                        />
                        <LegendRow
                          label="Blocked"
                          value={`${blockedUsers} (${blockedPercent}%)`}
                          tone="rose"
                        />
                      </div>
                    </div>
                  </article>
                </div>

                <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <h2 className="text-xl font-bold text-white">
                      Users Report Generation
                    </h2>
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={exportUsersPdf}
                        className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400"
                      >
                        Export PDF
                      </button>
                      <button
                        type="button"
                        onClick={exportUsersExcel}
                        className="rounded-lg border border-cyan-400/50 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 transition hover:bg-cyan-500/20"
                      >
                        Export Excel
                      </button>
                    </div>
                  </div>
                  <p className="mt-2 text-sm text-slate-300">
                    Includes user counts, status percentages, login metrics, and
                    full user detail rows.
                  </p>
                </article>
              </section>
            )}

            {activeCategory === "incidents" && (
              <section className="mt-6 grid gap-6">
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                  <MetricCard
                    label="Total Tickets"
                    value={incidents.length}
                    accent="cyan"
                  />
                  <MetricCard
                    label="Open + In Progress"
                    value={incidentStatusCounts.OPEN + incidentStatusCounts.IN_PROGRESS}
                    accent="amber"
                  />
                  <MetricCard
                    label="Resolved + Closed"
                    value={incidentStatusCounts.RESOLVED + incidentStatusCounts.CLOSED}
                    accent="emerald"
                  />
                  <MetricCard
                    label="Avg Resolution (hrs)"
                    value={incidentResolutionHours}
                    accent="rose"
                  />
                </div>

                <div className="grid gap-6 lg:grid-cols-2">
                  <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                    <h2 className="text-xl font-bold text-white">
                      Ticket Status Distribution
                    </h2>
                    <p className="mt-1 text-sm text-slate-300">
                      Bar graph of incident workflow status.
                    </p>
                    <div className="mt-5 space-y-3">
                      {Object.entries(incidentStatusCounts).map(([key, value]) => (
                        <HorizontalBarRow
                          key={key}
                          label={key.replace("_", " ")}
                          value={value}
                          max={Math.max(1, ...Object.values(incidentStatusCounts))}
                          colorClass={
                            key === "OPEN"
                              ? "from-rose-400 to-rose-500"
                              : key === "IN_PROGRESS"
                                ? "from-blue-400 to-blue-500"
                                : key === "REJECTED"
                                  ? "from-amber-400 to-amber-500"
                                  : "from-emerald-400 to-emerald-500"
                          }
                        />
                      ))}
                    </div>
                  </article>

                  <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                    <h2 className="text-xl font-bold text-white">
                      Priority Breakdown
                    </h2>
                    <p className="mt-1 text-sm text-slate-300">
                      Chart by LOW / MEDIUM / HIGH / CRITICAL.
                    </p>
                    <div className="mt-5 space-y-3">
                      {Object.entries(incidentPriorityCounts).map(([key, value]) => (
                        <HorizontalBarRow
                          key={key}
                          label={key}
                          value={value}
                          max={Math.max(1, ...Object.values(incidentPriorityCounts))}
                          colorClass={
                            key === "CRITICAL"
                              ? "from-rose-500 to-red-600"
                              : key === "HIGH"
                                ? "from-amber-400 to-orange-500"
                                : key === "MEDIUM"
                                  ? "from-cyan-400 to-cyan-500"
                                  : "from-emerald-400 to-emerald-500"
                          }
                        />
                      ))}
                    </div>
                  </article>
                </div>

                <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                  <h2 className="text-xl font-bold text-white">
                    Tickets Created (Last 6 Months)
                  </h2>
                  <p className="mt-1 text-sm text-slate-300">
                    Monthly incident creation trend chart.
                  </p>
                  <div className="mt-6 grid grid-cols-6 gap-3">
                    {incidentMonthlyTrend.map((month) => (
                      <div key={month.key} className="flex flex-col items-center">
                        <div className="flex h-28 items-end">
                          <div
                            className="w-8 rounded-t-lg bg-gradient-to-t from-cyan-500 to-blue-500"
                            style={{ height: `${Math.max(8, month.barPercent)}%` }}
                            title={`${month.label}: ${month.count}`}
                          />
                        </div>
                        <p className="mt-2 text-xs text-slate-300">{month.label}</p>
                        <p className="text-xs font-semibold text-cyan-300">
                          {month.count}
                        </p>
                      </div>
                    ))}
                  </div>
                </article>

                <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <h2 className="text-xl font-bold text-white">
                      Incident Report Generation
                    </h2>
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={exportIncidentsPdf}
                        className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400"
                      >
                        Export PDF
                      </button>
                      <button
                        type="button"
                        onClick={exportIncidentsExcel}
                        className="rounded-lg border border-cyan-400/50 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 transition hover:bg-cyan-500/20"
                      >
                        Export Excel
                      </button>
                    </div>
                  </div>
                  <p className="mt-2 text-sm text-slate-300">
                    Download incident analytics and detailed ticket data.
                  </p>

                  <div className="mt-5 overflow-x-auto">
                    <table className="min-w-full border-separate border-spacing-y-2">
                      <thead>
                        <tr className="text-left text-xs uppercase tracking-[0.2em] text-slate-400">
                          <th className="px-3 py-2">ID</th>
                          <th className="px-3 py-2">Resource</th>
                          <th className="px-3 py-2">Priority</th>
                          <th className="px-3 py-2">Status</th>
                          <th className="px-3 py-2">Assigned</th>
                        </tr>
                      </thead>
                      <tbody>
                        {incidents.length === 0 ? (
                          <tr>
                            <td
                              colSpan="5"
                              className="px-3 py-4 text-center text-slate-300"
                            >
                              No incident tickets available.
                            </td>
                          </tr>
                        ) : (
                          incidents.slice(0, 10).map((item) => (
                            <tr
                              key={item.id}
                              className="rounded-2xl bg-slate-950/60"
                            >
                              <td className="rounded-l-2xl px-3 py-3 text-sm font-semibold text-white">
                                #{item.id}
                              </td>
                              <td className="px-3 py-3 text-sm text-slate-300">
                                {item.resourceName || "-"}
                              </td>
                              <td className="px-3 py-3 text-sm text-slate-300">
                                {item.priority || "-"}
                              </td>
                              <td className="px-3 py-3 text-sm text-slate-300">
                                {item.status || "-"}
                              </td>
                              <td className="rounded-r-2xl px-3 py-3 text-sm text-slate-300">
                                {item.assignedToName || "-"}
                              </td>
                            </tr>
                          ))
                        )}
                      </tbody>
                    </table>
                  </div>
                </article>
              </section>
            )}

            {(activeCategory === "bookings" || activeCategory === "assets") && (
              <section className="mt-6 rounded-3xl border border-amber-400/30 bg-amber-500/10 p-6 text-amber-100">
                <h2 className="text-2xl font-black">
                  {activeCategory.toUpperCase()}
                </h2>
                <p className="mt-2 text-sm">
                  Not implemented yet. Reporting for this category will be added
                  in a future update.
                </p>
              </section>
            )}

            {activeCategory === "notifications" && (
              <section className="mt-6 grid gap-6">
                <div className="grid gap-4 sm:grid-cols-3">
                  <MetricCard
                    label="Total Notifications"
                    value={notifications.length}
                    accent="cyan"
                  />
                  <MetricCard
                    label="With Attachments"
                    value={notificationsWithAttachment}
                    accent="emerald"
                  />
                  <MetricCard
                    label="With Links"
                    value={notificationsWithLinks}
                    accent="amber"
                  />
                </div>

                <article className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5 shadow-xl shadow-cyan-950/10">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <h2 className="text-xl font-bold text-white">
                      Notifications Report Generation
                    </h2>
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={exportNotificationsPdf}
                        className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950 transition hover:bg-cyan-400"
                      >
                        Export PDF
                      </button>
                      <button
                        type="button"
                        onClick={exportNotificationsExcel}
                        className="rounded-lg border border-cyan-400/50 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 transition hover:bg-cyan-500/20"
                      >
                        Export Excel
                      </button>
                    </div>
                  </div>
                  <p className="mt-2 text-sm text-slate-300">
                    Includes notification metadata, attachment/link presence,
                    and creation timeline.
                  </p>

                  <div className="mt-5 overflow-x-auto">
                    <table className="min-w-full border-separate border-spacing-y-2">
                      <thead>
                        <tr className="text-left text-xs uppercase tracking-[0.2em] text-slate-400">
                          <th className="px-3 py-2">Title</th>
                          <th className="px-3 py-2">Creator</th>
                          <th className="px-3 py-2">Link</th>
                          <th className="px-3 py-2">Document</th>
                          <th className="px-3 py-2">Created At</th>
                        </tr>
                      </thead>
                      <tbody>
                        {notifications.length === 0 ? (
                          <tr>
                            <td
                              colSpan="5"
                              className="px-3 py-4 text-center text-slate-300"
                            >
                              No notifications available.
                            </td>
                          </tr>
                        ) : (
                          notifications.slice(0, 10).map((item) => (
                            <tr
                              key={item.id}
                              className="rounded-2xl bg-slate-950/60"
                            >
                              <td className="rounded-l-2xl px-3 py-3 text-sm font-semibold text-white">
                                {item.title}
                              </td>
                              <td className="px-3 py-3 text-sm text-slate-300">
                                {item.createdBy || "-"}
                              </td>
                              <td className="px-3 py-3 text-sm text-slate-300">
                                {item.linkUrl ? "Yes" : "No"}
                              </td>
                              <td className="px-3 py-3 text-sm text-slate-300">
                                {item.hasDocument
                                  ? item.documentName || "Yes"
                                  : "No"}
                              </td>
                              <td className="rounded-r-2xl px-3 py-3 text-sm text-slate-300">
                                {formatDate(item.createdAt)}
                              </td>
                            </tr>
                          ))
                        )}
                      </tbody>
                    </table>
                  </div>
                </article>
              </section>
            )}
          </>
        )}
      </section>
    </main>
  );
}

function MetricCard({ label, value, accent }) {
  const accents = {
    cyan: "border-cyan-500/30 bg-cyan-500/10 text-cyan-200",
    emerald: "border-emerald-500/30 bg-emerald-500/10 text-emerald-200",
    rose: "border-rose-500/30 bg-rose-500/10 text-rose-200",
    amber: "border-amber-500/30 bg-amber-500/10 text-amber-200",
  };

  return (
    <article className={`rounded-2xl border p-4 ${accents[accent]}`}>
      <p className="text-xs font-semibold uppercase tracking-[0.2em]">
        {label}
      </p>
      <p className="mt-2 text-3xl font-black text-white">{value}</p>
    </article>
  );
}

function LegendRow({ label, value, tone }) {
  const tones = {
    emerald: "bg-emerald-500",
    rose: "bg-rose-500",
  };

  return (
    <div className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950/70 px-3 py-2">
      <div className="flex items-center gap-2">
        <span className={`h-2.5 w-2.5 rounded-full ${tones[tone]}`} />
        <span className="text-slate-200">{label}</span>
      </div>
      <span className="font-semibold text-white">{value}</span>
    </div>
  );
}

function HorizontalBarRow({ label, value, max, colorClass }) {
  const percent = Math.round((value / Math.max(1, max)) * 100);
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-sm text-slate-200">
        <span>{label}</span>
        <span className="font-semibold">{value}</span>
      </div>
      <div className="h-2.5 rounded-full bg-slate-800">
        <div
          className={`h-2.5 rounded-full bg-gradient-to-r ${colorClass}`}
          style={{ width: `${Math.max(5, percent)}%` }}
        />
      </div>
    </div>
  );
}

export default Analytics;
